addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.10.4")
addSbtPlugin("org.scalameta"      % "sbt-native-image"         % "0.3.4")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.12.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.4.7")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"              % "0.6.4")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.12.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "2.1.1")
addSbtPlugin("nl.gn0s1s"          % "sbt-dotenv"               % "3.0.0")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.10.0")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"             % "0.5.2")
addSbtPlugin("com.guizmaii"       % "sbt-datadog"              % "5.0.3")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.16.0")
addDependencyTreePlugin
